[package]
name = "sozu"
description = "sozu, a fast, reliable, hot reconfigurable HTTP reverse proxy"
repository = "https://github.com/sozu-proxy/sozu"
readme = "README.md"
documentation = "https://docs.rs/sozu"
homepage = "https://sozu.io"
version = "1.0.6"
license = "AGPL-3.0"
authors = [
  "Geoffroy Couprie <geo.couprie@gmail.com>",
  "Eloi Demolis <eloi.demolis@clever-cloud.com>",
  "Emmanuel Bosquet <emmanuel.bosquet@clever-cloud.com>",
  "Florentin Dubois <florentin.dubois@clever-cloud.com>",
]
categories = ["network-programming"]
edition = "2024"
rust-version = "1.85.0"
include = ["README.md", "Cargo.toml", "src/**/*"]

[lib]
name = "sozu"
path = "src/lib.rs"

[[bin]]
name = "sozu"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
jemallocator = { workspace = true, optional = true }
libc = { workspace = true }
log = { workspace = true }
mio = { workspace = true, features = ["os-poll", "net"] }
nix = { workspace = true, features = ["signal", "fs"] }
nom = { workspace = true }
paw = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
prost = { workspace = true }
tempfile = { workspace = true }
termion = { workspace = true }
thiserror = { workspace = true }

sozu-command-lib = { workspace = true }
sozu-lib = { workspace = true }

[target.'cfg(target_os="linux")'.dependencies]
num_cpus = "^1.17.0"

[features]
default = ["jemallocator"]
unstable = []
logs-debug = ["sozu-lib/logs-debug", "sozu-command-lib/logs-debug"]
logs-trace = ["sozu-lib/logs-trace", "sozu-command-lib/logs-trace"]
opentelemetry = ["sozu-lib/opentelemetry"]
tolerant-http1-parser = ["sozu-lib/tolerant-http1-parser"]

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }
